baseURL = 'https://krh5284.github.io/traveler-camps/'
locale = 'en-us'
title = 'Traveler Camps'
theme = 'hugo-PaperMod'

[[menu.main]]
identifier = "contact-us"
name = "Contact Us"
url = "http://localhost:1313/traveler-camps/contact-us/"
weight = 10

[[menu.main]]
identifier = "new-job-site"
name = "New Job Site Request"
url = "http://localhost:1313/traveler-camps/new-job-site/"
weight = 20

[[menu.main]]
identifier = "new-campgroud"
name = "New Campground Request"
url = "http://localhost:1313/traveler-camps/new-campground/"
weight = 30

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modulegitinfo]
    dir = ':cacheDir/modules'
    maxAge = '24h'
  [caches.modulequeries]
    dir = ':cacheDir/modules'
    maxAge = '24h'
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

